import {waitForCanvasReady} from './helpers/browserReady.mjs';
import {chromium} from '@playwright/test';
import {tsImport} from 'tsx/esm/api';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import {createHash} from 'node:crypto';
import {spawnSync} from 'node:child_process';

// App changes use physical browser input/navigation only. Diagnostics observe.
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const output=process.env.ROOM_TEST_OUTPUT??path.join(root,'validation/v06a');
const production=process.env.ROOM_TEST_PRODUCTION==='1';
const performanceOnly=process.env.ROOM_FURNITURE_PERFORMANCE_ONLY==='1';
const origin=process.env.ROOM_TEST_URL??`http://127.0.0.1:${production?'3001':'3000'}`;
const {assetManifest,assetFamilies,furnitureFamilies}=await tsImport('../lib/room/assets/assetManifest.ts',import.meta.url);
const expectedA=['floor','walls','door','window','curtains','desk','cabinet','bed','bedside','sofa','chair','coffee','sidetable','beanbag','rugs','dogbed'];
assert.deepEqual([...furnitureFamilies].sort(),[...expectedA].sort(),'Every authorized A family must be registered');
const authorizedB=['piano','ipad','phone','trashcan','lightswitch','keyboard','mouse','headphones'];
assert.deepEqual([...assetFamilies].sort(),['monitor','macbook','marshall',...expectedA,...authorizedB.filter(id=>assetFamilies.includes(id))].sort(),'Exactly the protected old three, A16 and registered B families must be present');
const ids=['monitor','macbook','ipad','marshall','piano','trashcan','lightswitch','phone','window'];
const titles={monitor:'Projects',macbook:'About / Education',ipad:'Memories',marshall:'Music',piano:'Piano',trashcan:'Deleted ideas',lightswitch:'Room lights',phone:'Contact',window:'Environment'};
const viewports=[{width:1440,height:900},{width:768,height:1024},{width:390,height:844}];
const baseline=JSON.parse(await fs.readFile(path.join(root,'validation/v06a/baseline/hero-performance.json'),'utf8'));
const baselineActivity=JSON.parse(await fs.readFile(path.join(root,'validation/v06a/baseline/activity-performance.json'),'utf8'));
const checks=[],runtime=[],requests=[],observations={};
const contexts=new Set();
async function exportHashes(){return Object.fromEntries(await Promise.all(assetFamilies.map(async id=>[id,createHash('sha256').update(await fs.readFile(path.join(root,'public',assetManifest[id].url))).digest('hex')])));}
observations.exportHashesAtStart=await exportHashes();
await fs.mkdir(output,{recursive:true});
const browser=await chromium.launch({executablePath:process.env.CHROME_PATH??'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true,args:['--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader']});
const snap=page=>page.evaluate(()=>window.__ROOM_DEBUG__?.snapshot());
const sorted=value=>[...value].sort();
function observe(page,phase){page.on('pageerror',e=>runtime.push({phase,type:'pageerror',text:e.message}));page.on('console',m=>{if(['error','warning'].includes(m.type()))runtime.push({phase,type:m.type(),text:m.text()});});page.on('requestfailed',r=>requests.push({phase,url:r.url(),error:r.failure()?.errorText}));}
async function contextFor(viewport=viewports[0],{video=false,reduced=false}={}){const context=await browser.newContext({viewport,deviceScaleFactor:1,hasTouch:viewport.width===390,isMobile:viewport.width===390,reducedMotion:reduced?'reduce':'no-preference',...(video?{recordVideo:{dir:path.join(output,'raw-video'),size:viewports[0]}}:{})});contexts.add(context);return context;}
async function close(context){await context.close();contexts.delete(context);}
async function loaded(page,expected={}){
  await page.waitForSelector('[data-room-status="ready"]',{timeout:90000});
  for(const family of assetFamilies)await page.waitForSelector(`[data-asset-${family}="${expected[family]??'installed'}"]`,{timeout:15000});
  if(production)return null;
  const state=await snap(page);assert(state,'Read-only development diagnostics are required');assert.equal(state.assembly.ok,true,JSON.stringify(state.assembly));assert.deepEqual(state.assembly.errors,[]);assert.equal(state.assembly.sourceNodeCount,85);assert.equal(state.validation.nodeCount,85);
  assert.deepEqual(state.validation.mappings,baseline.samples[0].snapshot.validation.mappings,'Original nine targets and 14-node mappings changed');
  assert.deepEqual(sorted(Object.keys(state.assets)),sorted(assetFamilies));
  for(const family of assetFamilies){const status=expected[family]??'installed';assert.equal(state.assets[family].status,status);assert.equal(state.assembly.installedFamilies.includes(family),status==='installed');assert.equal(state.assetVisuals[family].meshes>0,status==='installed');}
  return state;
}
async function open({viewport=viewports[0],phase='normal',video=false,reduced=false,continuous=false,debug=true}={}){const context=await contextFor(viewport,{video,reduced}),page=await context.newPage();observe(page,phase);await page.goto(`${origin}/${debug?`?debug=1${continuous?'':'&demand=1'}`:''}`,{waitUntil:'domcontentloaded'});if(debug)await loaded(page);else{await page.waitForSelector('[data-room-status="ready"]',{timeout:90000});for(const family of assetFamilies)await page.waitForSelector(`[data-asset-${family}="installed"]`);}return page;}
async function screen(page,file,clip){await page.screenshot({path:path.join(output,file),style:'.debug-panel {visibility:hidden !important;}',...(clip?{clip}:{})});return file;}
async function check(name,fn,page){try{const detail=await fn();checks.push({name,passed:true,...detail});console.log(`PASS ${name}`);}catch(error){const failure={name,passed:false,error:String(error.stack??error)};if(page&&!page.isClosed()){failure.snapshot=await snap(page).catch(()=>null);failure.body=await page.locator('body').innerText().catch(()=>'');await screen(page,`furniture-failure-${checks.length+1}.png`).catch(()=>{});}checks.push(failure);console.log(`FAIL ${name}: ${error.message}`);throw error;}}
async function quiet(page){await page.mouse.move(0,0);await page.waitForTimeout(100);return snap(page);}
async function stateIs(page,expected){await page.waitForFunction(expected=>{const s=window.__ROOM_DEBUG__?.snapshot().interaction;return s&&Object.entries(expected).every(([key,value])=>s[key]===value);},expected,{timeout:20000});}
async function input(page,point,touch=false){if(!production)(observations.nativeInputs??=[]).push(await page.evaluate(point=>({point,rect:document.querySelector('canvas').getBoundingClientRect().toJSON(),hit:window.__ROOM_DEBUG__?.hitTest(point.x,point.y)}),point));if(touch)await page.touchscreen.tap(point.x,point.y);else await page.mouse.click(point.x,point.y);}
async function stableCanvas(page,id){const settled=await waitForCanvasReady(page,{interactionId:id});(observations.layoutWaits??=[]).push(settled);return settled;}
async function pointFor(page,id,family=null){
  await stableCanvas(page,id);
  const result=await page.evaluate(({id,family})=>{
    const api=window.__ROOM_DEBUG__,canvas=document.querySelector('canvas'),r=canvas.getBoundingClientRect();
    const inspect=point=>{if(!point||document.elementFromPoint(point.x,point.y)!==canvas)return null;const hit=api.hitTest(point.x,point.y);return hit?.semanticId===id&&(!family||hit.assetFamily===family)?{point,hit}:null;};
    const direct=inspect(api.projected()[id]);if(direct)return direct;
    for(const step of [8,3,1])for(let y=Math.ceil(r.y)+1;y<r.bottom;y+=step)for(let x=Math.ceil(r.x)+1;x<r.right;x+=step){const result=inspect({x,y});if(result)return result;}
    return null;
  },{id,family});
  assert(result,`No visible native pixel for ${id}${family?` on ${family} production geometry`:''}`);if(family)assert.equal(result.hit.assetFamily,family);return result;
}
const requiredFamily=id=>assetFamilies.includes(id)?id:null;
async function activate(page,id,touch=false){const target=await pointFor(page,id,requiredFamily(id));await input(page,target.point,touch);await stateIs(page,{activeObject:id,interactionPhase:'focused',isCameraBusy:false});await page.getByRole('heading',{name:titles[id],exact:true}).waitFor();return {target,state:await quiet(page)};}
async function back(page,hero,touch=false){const b=page.getByRole('button',{name:'Back',exact:true});if(touch)await b.tap();else await b.click();await stateIs(page,{activeObject:null,isCameraBusy:false});const state=await quiet(page);if(hero)assert.deepEqual(state.camera,hero,'Original Hero must return exactly');assert.equal(state.assembly.ok,true);assert.equal(state.interaction.error,null);return state;}
async function visibleRegions(page){return page.evaluate(()=>{const api=window.__ROOM_DEBUG__,canvas=document.querySelector('canvas'),r=canvas.getBoundingClientRect(),regions={};for(let y=Math.ceil(r.y)+6;y<r.bottom;y+=10)for(let x=Math.ceil(r.x)+6;x<r.right;x+=10){if(document.elementFromPoint(x,y)!==canvas)continue;const hit=api.hitTest(x,y);if(!hit?.assetFamily)continue;const current=regions[hit.assetFamily]??{minX:x,minY:y,maxX:x,maxY:y,point:{x,y},hit,pixels:0};current.minX=Math.min(current.minX,x);current.maxX=Math.max(current.maxX,x);current.minY=Math.min(current.minY,y);current.maxY=Math.max(current.maxY,y);current.pixels++;regions[hit.assetFamily]=current;}return {regions,canvas:{x:r.x,y:r.y,width:r.width,height:r.height}};});}
function regionClip(regions,ids,viewport){const entries=ids.map(id=>regions[id]).filter(Boolean);assert(entries.length,`No visible crop regions ${ids}`);const x=Math.max(0,Math.floor(Math.min(...entries.map(r=>r.minX))-18)),y=Math.max(0,Math.floor(Math.min(...entries.map(r=>r.minY))-18));return {x,y,width:Math.min(viewport.width-x,Math.ceil(Math.max(...entries.map(r=>r.maxX))-x+18)),height:Math.min(viewport.height-y,Math.ceil(Math.max(...entries.map(r=>r.maxY))-y+18))};}
function resourceShape(state){return {runtimeNodeCount:state.assembly.runtimeNodeCount,rendererMemory:state.rendererMemory??null,families:Object.fromEntries(assetFamilies.map(id=>{const v=state.assetVisuals[id];return [id,{meshes:v.meshes,materials:v.materials,triangles:v.triangles,textures:v.textures.map(t=>({name:t.name,width:t.width,height:t.height,colorSpace:t.colorSpace,estimatedRGBABytesWithMipmaps:t.estimatedRGBABytesWithMipmaps}))}];}))};}
function textureLedger(state){const instances=assetFamilies.flatMap(family=>state.assetVisuals[family].textures.map(texture=>({family,...texture})));const unique=new Map(instances.map(texture=>[texture.uuid,texture]));return {instances,reportedInstances:instances.length,uniqueTextureUuids:unique.size,estimatedUniqueRGBABytesWithMipmaps:[...unique.values()].reduce((sum,texture)=>sum+texture.estimatedRGBABytesWithMipmaps,0),rendererMemory:state.rendererMemory,limits:'UUIDs identify renderer texture objects; mipmapped RGBA estimates are not measured GPU allocations.'};}
async function rejectStaticHits(page,regions,touch=false){const verified=[];for(const family of ['desk','chair','floor']){const target=regions[family];assert(target,`Visible ${family} production surface required for occlusion check`);const hit=await page.evaluate(p=>window.__ROOM_DEBUG__.hitTest(p.x,p.y),target.point);assert.equal(hit.assetFamily,family);assert.equal(hit.semanticId,null,`${family} must occlude, not become a semantic button`);await input(page,target.point,touch);assert.equal((await snap(page)).interaction.activeObject,null);verified.push({family,point:target.point,hit});}return verified;}
async function pianoReopen(page,hero,touch=false,{images=false}={}){
  await activate(page,'piano',touch);
  if((await snap(page)).interaction.pianoState!=='extended'){const b=page.getByRole('button',{name:'Toggle piano',exact:true});if(touch)await b.tap();else await b.click();await stateIs(page,{pianoState:'extended',interactionPhase:'focused'});}
  if(images)await screen(page,'workstation_piano_extended.png');
  const toggle=page.getByRole('button',{name:'Toggle piano',exact:true});if(touch)await toggle.tap();else await toggle.click();await stateIs(page,{pianoState:'retracted',interactionPhase:'focused'});
  assert.equal((await snap(page)).mechanical.transforms.piano.position[2],-1.9399999618530273);
  if(images)await screen(page,'workstation_piano_retracted.png');await back(page,hero,touch);
  const negatives=await rejectStaticHits(page,(await visibleRegions(page)).regions,touch);
  const target=await pointFor(page,'piano');assert.equal(target.hit.runtimeTarget,'PianoRetractedHitArea');
  if(!touch){await page.mouse.move(target.point.x,target.point.y);await page.locator('.page-footer p').filter({hasText:'Pull-out Piano'}).waitFor();}
  await input(page,target.point,touch);await stateIs(page,{pianoState:'extended',interactionPhase:'focused'});
  const state=await snap(page);assert.equal(state.mechanical.transforms.piano.position[2],-1.2899999618530273);assert.equal(state.pianoRetractedHitAreaActive,false);
  if(images)await screen(page,'piano_reopen_from_desk.png');await back(page,hero,touch);return {target,negatives,withoutExploreObjects:true,travel:.65};
}
function corruptImage(bytes){const copy=Buffer.from(bytes),length=copy.readUInt32LE(12),json=JSON.parse(copy.toString('utf8',20,20+length)),image=json.images?.find(i=>i.bufferView!==undefined);if(!image)return null;const view=json.bufferViews[image.bufferView];assert.equal(view.buffer,0);const start=20+length+8+(view.byteOffset??0);copy.fill(0,start,start+view.byteLength);return {body:copy,mimeType:image.mimeType,bytes:view.byteLength};}
async function startupObserver(page){await page.addInitScript(families=>{window.__furnitureLoads=[];let previous='';const observer=new MutationObserver(()=>{const main=document.querySelector('[data-room-status]');if(!main)return;const state={room:main.getAttribute('data-room-status'),assets:Object.fromEntries(families.map(id=>[id,main.getAttribute(`data-asset-${id}`)]))},key=JSON.stringify(state);if(key!==previous){window.__furnitureLoads.push({atMs:performance.now(),...state});previous=key;}});observer.observe(document,{attributes:true,childList:true,subtree:true});},assetFamilies);}
async function recordActivity(page,label,action){await page.evaluate(()=>{window.__furnitureFrames=[];window.__furnitureSampling=true;function sample(){const s=window.__ROOM_DEBUG__.snapshot();window.__furnitureFrames.push({atMs:performance.now(),renderFrames:s.renderFrames,phase:s.interaction.interactionPhase,cameraBusy:s.interaction.isCameraBusy,activeObject:s.interaction.activeObject,macbookState:s.interaction.macbookState,pianoState:s.interaction.pianoState});if(window.__furnitureSampling)requestAnimationFrame(sample);}sample();});await action();const samples=await page.evaluate(()=>{window.__furnitureSampling=false;return window.__furnitureFrames;}),intervals=[];const active=s=>s.cameraBusy||['focusing','interacting','returning'].includes(s.phase);for(let i=1;i<samples.length;i++){const a=samples[i-1],b=samples[i],frames=b.renderFrames-a.renderFrames,elapsed=b.atMs-a.atMs;if(frames>0&&elapsed>0&&elapsed<250&&active(a)&&active(b))intervals.push(elapsed/frames);}assert(intervals.length>0);const s=[...intervals].sort((a,b)=>a-b);return {label,sampleCount:samples.length,renderedActiveIntervals:intervals.length,observedIntervalMs:{mean:intervals.reduce((a,b)=>a+b,0)/intervals.length,median:s[Math.floor(s.length*.5)],p95:s[Math.min(s.length-1,Math.floor(s.length*.95))],max:s.at(-1)},samples};}
let video,videoPath;
try{
  if(production){
    const evidence=JSON.parse(await fs.readFile(process.env.ROOM_FURNITURE_DEV_EVIDENCE??path.join(root,'validation/v06a/furniture-browser.json'),'utf8'));assert.equal(evidence.summary.failed,0);
    for(const viewport of [viewports[0],viewports[2]]){
      const touch=viewport.width===390,page=await open({viewport,phase:`production-${viewport.width}`}),record=evidence.observations.viewports[viewport.width];
      await check(`Production ${viewport.width}px installs all ${assetFamilies.length} registered families and refuses debug exposure`,async()=>{assert.equal(await page.evaluate(()=>Boolean(window.__ROOM_DEBUG__)),false);assert.equal(await page.locator('.debug-panel').count(),0);await screen(page,`production_${viewport.width}.png`);return {families:assetFamilies,debugAbsent:true};},page);
      for(const id of ids)await check(`Production ${viewport.width}px native ${id} entry and Back use recorded visible pixels`,async()=>{const target=record.initialPoints[id];if(requiredFamily(id))assert.equal(target.hit.assetFamily,id);await input(page,target.point,touch);await page.waitForSelector('[data-interaction-phase="focused"]',{timeout:20000});await page.getByRole('heading',{name:titles[id],exact:true}).waitFor();if(id==='lightswitch'&&await page.getByRole('button',{name:'Lights: Off',exact:true}).count()){const light=page.getByRole('button',{name:'Lights: Off',exact:true});if(touch)await light.tap();else await light.click();await page.getByRole('button',{name:'Lights: On',exact:true}).waitFor();}const b=page.getByRole('button',{name:'Back',exact:true});if(touch)await b.tap();else await b.click();await page.waitForSelector('[data-interaction-phase="idle"]',{timeout:20000});assert.equal(await page.evaluate(()=>Boolean(window.__ROOM_DEBUG__)),false);return {target,nativeInput:touch?'touch':'mouse'};},page);
      await check(`Production ${viewport.width}px reopens retracted Piano through the desk with all ${assetFamilies.length} registered families installed`,async()=>{await input(page,record.initialPoints.piano.point,touch);await page.waitForSelector('[data-interaction-phase="focused"]',{timeout:20000});const text=await page.locator('.interaction-overlay').innerText();if(!text.includes('Piano: retracted')){const t=page.getByRole('button',{name:'Toggle piano',exact:true});if(touch)await t.tap();else await t.click();await page.getByText('Piano: retracted',{exact:true}).waitFor();}const b=page.getByRole('button',{name:'Back',exact:true});if(touch)await b.tap();else await b.click();await page.waitForSelector('[data-interaction-phase="idle"]');await input(page,record.piano.target.point,touch);await page.waitForSelector('[data-interaction-phase="focused"]',{timeout:20000});await page.getByText('Piano: extended',{exact:true}).waitFor();return {target:record.piano.target,withoutExploreObjects:true};},page);
      await close(page.context());
    }
  }else if(performanceOnly){
    observations.performance=[];observations.activity=[];
    for(const viewport of viewports){
      const context=await contextFor(viewport),page=await context.newPage();observe(page,`performance-${viewport.width}`);await startupObserver(page);
      await page.goto(`${origin}/?debug=1`,{waitUntil:'domcontentloaded'});await loaded(page);await page.waitForFunction(()=>window.__ROOM_DEBUG__.snapshot().performance?.calls>0,undefined,{timeout:30000});
      await check(`Isolated ${viewport.width}px Hero, loading, network and texture resources compare with actual v0.5 baseline`,async()=>{const before=await snap(page);await page.waitForTimeout(1500);const state=await snap(page),old=baseline.samples.find(s=>s.viewport.width===viewport.width);assert.deepEqual(state.camera,old.snapshot.camera);for(const id of ['monitor','macbook'])assert.deepEqual(state.assetVisuals[id].stateSurfaces.map(s=>s.textureUpdates),before.assetVisuals[id].stateSurfaces.map(s=>s.textureUpdates));const environment=await page.evaluate(()=>{const c=document.querySelector('canvas'),gl=c.getContext('webgl2'),e=gl.getExtension('WEBGL_debug_renderer_info');return {dpr:devicePixelRatio,userAgent:navigator.userAgent,canvas:{width:c.width,height:c.height},renderer:e?gl.getParameter(e.UNMASKED_RENDERER_WEBGL):gl.getParameter(gl.RENDERER),resources:performance.getEntriesByType('resource').filter(r=>r.name.includes('/models/')).map(r=>({name:r.name,transferSize:r.transferSize,encodedBodySize:r.encodedBodySize,decodedBodySize:r.decodedBodySize,duration:r.duration})),loadMilestones:window.__furnitureLoads};});assert.equal(environment.dpr,1);const firstReadyMs=environment.loadMilestones.find(value=>value.room==='ready')?.atMs,allFamiliesInstalledMs=environment.loadMilestones.find(value=>assetFamilies.every(id=>value.assets[id]==='installed'))?.atMs;assert(Number.isFinite(firstReadyMs)&&Number.isFinite(allFamiliesInstalledMs));const current={viewport,baseline:old.snapshot.performance,current:state.performance,addedCalls:state.performance.calls-old.snapshot.performance.calls,intervalDeltaMs:state.performance.frameMs-old.snapshot.performance.frameMs,firstReadyMs,allFamiliesInstalledMs,environment,resources:resourceShape(state),textureLedger:textureLedger(state)};observations.performance.push(current);await screen(page,`performance_hero_${viewport.width}.png`);return current;},page);
      if(viewport.width!==768){const hero=(await snap(page)).camera,actions=[],focus=[];for(const id of ['monitor','macbook','marshall','piano']){actions.push(await recordActivity(page,`${id}: Hero to focus and mechanism`,()=>activate(page,id,viewport.width===390)));await page.mouse.move(0,0);await page.waitForTimeout(1500);const s=await snap(page);focus.push({id,camera:s.camera,performance:s.performance,mechanical:s.mechanical});actions.push(await recordActivity(page,`${id}: Back including mechanism exit`,()=>back(page,hero,viewport.width===390)));}const old=baselineActivity.results.find(r=>r.viewport.width===viewport.width);observations.activity.push({viewport,actions,focus,baselineFirstReadyMs:old.firstReadyMs,baselineActions:old.actions.map(a=>({label:a.label,observedIntervalMs:a.observedIntervalMs})),baselineFocus:old.focus.map(f=>({id:f.id,performance:f.performance}))});}
      await close(context);
    }
    observations.fallbackTimings=[];
    for(const {family,kind} of [{family:'floor',kind:'404'},{family:'bed',kind:'corrupt-image'}]){
      const context=await contextFor(),page=await context.newPage();observe(page,`fault-timing-${family}`);await startupObserver(page);
      const fixture=kind==='corrupt-image'?corruptImage(await fs.readFile(path.join(root,'public',assetManifest[family].url))):null;
      if(kind==='corrupt-image')assert(fixture,'The representative bed fixture must contain an embedded image');
      await page.route(`**${assetManifest[family].url}`,route=>route.fulfill(kind==='404'?{status:404,contentType:'text/plain',body:'Intentional timed one-family failure'}:{status:200,contentType:'model/gltf-binary',body:fixture.body}));
      await page.goto(`${origin}/?debug=1&demand=1`,{waitUntil:'domcontentloaded'});
      await check(`Timed ${family} ${kind} fallback is atomic and native refresh restores every family`,async()=>{
        const state=await loaded(page,{[family]:'fallback'});assert.equal(state.assetVisuals[family].meshes,0);assert.equal(state.assembly.installedFamilies.length,assetFamilies.length-1);
        const failedNavigation=await page.evaluate(()=>({timeOrigin:performance.timeOrigin,milestones:window.__furnitureLoads}));
        failedNavigation.firstFallbackMs=failedNavigation.milestones.find(value=>value.assets[family]==='fallback')?.atMs;
        failedNavigation.firstReadyMs=failedNavigation.milestones.find(value=>value.room==='ready')?.atMs;
        assert(Number.isFinite(failedNavigation.firstFallbackMs)&&Number.isFinite(failedNavigation.firstReadyMs));
        await page.unroute(`**${assetManifest[family].url}`);await page.getByRole('button',{name:'刷新重试',exact:true}).click();const restored=await loaded(page);
        const retryNavigation=await page.evaluate(()=>({timeOrigin:performance.timeOrigin,milestones:window.__furnitureLoads}));
        retryNavigation.allRegisteredInstalledMs=retryNavigation.milestones.find(value=>assetFamilies.every(id=>value.assets[id]==='installed'))?.atMs;
        retryNavigation.firstReadyMs=retryNavigation.milestones.find(value=>value.room==='ready')?.atMs;
        assert(Number.isFinite(retryNavigation.allRegisteredInstalledMs)&&Number.isFinite(retryNavigation.firstReadyMs));assert(retryNavigation.timeOrigin>failedNavigation.timeOrigin);
        const timing={family,kind,failedNavigation,retryNavigation,error:state.assets[family].error,fallbackVisualMeshes:state.assetVisuals[family].meshes,otherInstalledFamilies:state.assembly.installedFamilies,retryInstalledFamilies:restored.assembly.installedFamilies,expectedFallback:true,countsAsFormalPass:false,nativeRefresh:true,note:'Times are performance.now milliseconds within each separately identified navigation. Observed DOM fallback/installed reports; local warm server and fresh browser context, not internet cold-start latency.'};
        observations.fallbackTimings.push(timing);return timing;
      },page);await close(context);
    }
    const files=['/models/sharkys_room_blockout_FINAL.glb',...assetFamilies.map(id=>assetManifest[id].url)];observations.modelFiles=[];for(const url of files){const data=await fs.readFile(path.join(root,'public',url));observations.modelFiles.push({url,bytes:data.length,sha256:createHash('sha256').update(data).digest('hex')});}
  }else{
    observations.viewports={};
    await fs.copyFile(path.join(root,'validation/v06a/baseline/hero-1440.png'),path.join(output,'hero_before.png'));
    for(const viewport of viewports){
      const touch=viewport.width===390,desktop=viewport.width===1440,page=await open({viewport,phase:`normal-${viewport.width}`,video:desktop&&process.env.ROOM_TEST_VIDEO!=='0'});if(desktop)video=page.video();
      const initial=await quiet(page),hero=initial.camera,entry={initial,initialPoints:{}};observations.viewports[viewport.width]=entry;
      await check(`${viewport.width}×${viewport.height} shows all A16 plus original three families with exact frozen targets`,async()=>{assert.deepEqual(sorted(initial.assembly.installedFamilies),sorted(assetFamilies));assert.equal(initial.validation.mappings.reduce((n,m)=>n+m.nodeNames.length,0),14);assert(initial.assembly.runtimeNodeCount>baseline.samples[0].snapshot.assembly.runtimeNodeCount);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);for(const id of ids)entry.initialPoints[id]=await pointFor(page,id,requiredFamily(id));await screen(page,desktop?'hero_after.png':touch?'mobile_390.png':'narrow_768.png');return {assembly:initial.assembly,assetVisuals:initial.assetVisuals,actualWindowTarget:entry.initialPoints.window};},page);
      const regions=await visibleRegions(page);entry.regions=regions;
      await check(`${viewport.width}px visible desk, chair and floor stop rays without becoming semantic controls`,async()=>({negativeHits:await rejectStaticHits(page,regions.regions,touch)}),page);
      if(desktop){await screen(page,'cabinet_compartments.png',regionClip(regions.regions,['cabinet'],viewport));await screen(page,'furniture_seating_bed.png',regionClip(regions.regions,['bed','sofa','chair','beanbag'],viewport));}
      const testedIds=desktop?ids:['window','monitor','macbook','marshall'];
      for(const id of testedIds)await check(`${viewport.width}px native ${id} focus retains a real visible target and clear Back`,async()=>{const result=await activate(page,id,touch),focused=await pointFor(page,id,requiredFamily(id));const box=await page.getByRole('button',{name:'Back',exact:true}).boundingBox();assert(box&&box.width>=40&&box.height>=40&&box.x>=0&&box.y+box.height<=viewport.height);if(id==='window'){const rainy=page.getByRole('button',{name:'Rainy',exact:true});if(touch)await rainy.tap();else await rainy.click();await stateIs(page,{weather:'Rainy'});const sunny=page.getByRole('button',{name:'Sunny',exact:true});if(touch)await sunny.tap();else await sunny.click();}if(id==='lightswitch'&&(await snap(page)).interaction.lightsState==='off'){await page.getByRole('button',{name:'Lights: Off',exact:true}).click();await stateIs(page,{lightsState:'on',interactionPhase:'focused'});}await screen(page,desktop?`focus_${id}.png`:`focus_${viewport.width}_${id}.png`);await back(page,hero,touch);return {entryTarget:result.target,focusedTarget:focused,back:box};},page);
      if(desktop||touch)await check(`${viewport.width}px desk piano rediscovery works without the selector and retains neighbouring occlusion`,async()=>{entry.piano=await pianoReopen(page,hero,touch,{images:desktop});return entry.piano;},page);
      await check(`${viewport.width}px demand rendering rests after furniture, camera and mechanism activity`,async()=>{await quiet(page);await page.waitForTimeout(500);const a=await snap(page);await page.waitForTimeout(600);const b=await snap(page);assert.equal(b.renderFrames,a.renderFrames);assert.equal(b.assembly.ok,true);return {renderFrames:a.renderFrames};},page);
      await close(page.context());if(desktop&&video)videoPath=await video.path();
    }
    const normal=await open({phase:'normal-no-debug',debug:false});await check('Default development rendering exposes neither diagnostics nor hit-area UI',async()=>{assert.equal(await normal.evaluate(()=>Boolean(window.__ROOM_DEBUG__)),false);assert.equal(await normal.locator('.debug-panel').count(),0);return {debugAbsent:true};},normal);await close(normal.context());
    for(const family of furnitureFamilies){
      const context=await contextFor(viewports[0],{reduced:true}),page=await context.newPage();observe(page,`fault-404-${family}`);await page.route(`**${assetManifest[family].url}`,route=>route.fulfill({status:404,contentType:'text/plain',body:'Intentional one-family failure'}));await page.goto(`${origin}/?debug=1&demand=1`,{waitUntil:'domcontentloaded'});
      await check(`${family}: isolated GLB404 keeps the full proxy family and all other ${assetFamilies.length-1} formal families`,async()=>{const state=await loaded(page,{[family]:'fallback'});assert.equal(state.assembly.installedFamilies.length,assetFamilies.length-1);assert(state.assets[family].error?.includes('404'));assert.equal(state.assetVisuals[family].meshes,0);await page.locator('.asset-fallback').filter({hasText:assetManifest[family].label}).waitFor();await activate(page,'monitor');await back(page,state.camera);await page.unroute(`**${assetManifest[family].url}`);await page.getByRole('button',{name:'刷新重试',exact:true}).click();const retry=await loaded(page);assert.equal(retry.assembly.installedFamilies.length,assetFamilies.length);return {expectedFallback:true,countsAsFormalPass:false,error:state.assets[family].error,otherFamilies:state.assembly.installedFamilies,retryInstalled:true};},page);await close(context);
    }
    const textureCandidates=[];for(const family of furnitureFamilies){const fixture=corruptImage(await fs.readFile(path.join(root,'public',assetManifest[family].url)));if(fixture)textureCandidates.push({family,fixture});}
    assert(textureCandidates.length>0,'At least one A texture must exercise real image-decode fallback');
    const architectureTexture=textureCandidates[0],furnitureTexture=textureCandidates.find(item=>['bed','sofa','chair','beanbag','rugs','dogbed'].includes(item.family));
    for(const {family,fixture} of [...new Map([architectureTexture,furnitureTexture].filter(Boolean).map(item=>[item.family,item])).values()]){
      const context=await contextFor(viewports[0],{reduced:true}),page=await context.newPage();observe(page,`fault-texture-${family}`);await page.route(`**${assetManifest[family].url}`,route=>route.fulfill({status:200,contentType:'model/gltf-binary',body:fixture.body}));await page.goto(`${origin}/?debug=1&demand=1`,{waitUntil:'domcontentloaded'});
      await check(`${family}: corrupted embedded image prevents every partial visual from being installed`,async()=>{const state=await loaded(page,{[family]:'fallback'});assert(state.assets[family].error);assert.equal(state.assetVisuals[family].meshes,0);assert.equal(state.assembly.installedFamilies.length,assetFamilies.length-1);await page.unroute(`**${assetManifest[family].url}`);await page.getByRole('button',{name:'刷新重试',exact:true}).click();await loaded(page);return {expectedFallback:true,countsAsFormalPass:false,error:state.assets[family].error,corruptedImageBytes:fixture.bytes,mimeType:fixture.mimeType,retryInstalled:true};},page);await close(context);
    }
    {
      const context=await contextFor(),page=await context.newPage();observe(page,'cancel-reload');let entered,release;const requested=new Promise(resolve=>{entered=resolve;}),gate=new Promise(resolve=>{release=resolve;});await page.route(`**${assetManifest.desk.url}`,async route=>{entered();await gate;await route.continue().catch(()=>{});});
      await check('Delayed desk load can be abandoned; repeated reloads preserve one complete assembly and stable resource counts',async()=>{await page.goto(`${origin}/?debug=1&demand=1`,{waitUntil:'domcontentloaded'});let timer;try{await Promise.race([requested,new Promise((_,reject)=>{timer=setTimeout(()=>reject(new Error('No delayed desk request')),30000);})]);}finally{clearTimeout(timer);}await page.goto('about:blank');release();await page.unroute(`**${assetManifest.desk.url}`);await page.waitForTimeout(300);assert.equal(await page.evaluate(()=>Boolean(window.__ROOM_DEBUG__)),false);const shapes=[];for(let cycle=0;cycle<3;cycle++){await page.goto(`${origin}/?debug=1&demand=1`,{waitUntil:'domcontentloaded'});await loaded(page);await page.waitForTimeout(150);shapes.push(resourceShape(await snap(page)));await page.goto('about:blank');}assert.deepEqual(shapes[1],shapes[0]);assert.deepEqual(shapes[2],shapes[0]);return {cancelledDuringLoad:true,assemblies:shapes,limitation:'Stable renderer/resource counters and no stale page errors; this is not an exact GPU-memory leak measurement.'};},page);release();await close(context);
    }
  }
  await check('All registered exported GLBs remain unchanged throughout this evidence run',async()=>{observations.exportHashesAtEnd=await exportHashes();assert.deepEqual(observations.exportHashesAtEnd,observations.exportHashesAtStart);return {sha256:observations.exportHashesAtEnd};});
  await check('Normal A-batch sessions have no runtime errors; injected fault diagnostics stay isolated',async()=>{assert.deepEqual(runtime.filter(r=>r.type==='pageerror'),[]);assert.deepEqual(runtime.filter(r=>r.type==='error'&&!r.phase.startsWith('fault-')&&r.phase!=='cancel-reload'),[]);assert.deepEqual(requests.filter(r=>!r.phase.startsWith('fault-')&&r.phase!=='cancel-reload'),[]);return {normalErrors:0};});
}catch(error){if(!checks.some(c=>!c.passed))checks.push({name:'Furniture suite setup or execution',passed:false,error:String(error.stack??error)});process.exitCode=1;}
finally{
  for(const context of contexts)await context.close().catch(()=>{});if(!videoPath&&video)videoPath=await video.path().catch(()=>undefined);await browser.close();
  if(videoPath){const target=path.join(output,'interaction_regression.mp4'),converted=spawnSync(process.env.FFMPEG_PATH??'/opt/homebrew/bin/ffmpeg',['-y','-i',videoPath,'-c:v','libx264','-preset','fast','-crf','23','-pix_fmt','yuv420p','-movflags','+faststart',target],{encoding:'utf8'});observations.video={source:path.relative(root,videoPath),mp4:converted.status===0?path.relative(root,target):null,exitCode:converted.status,error:converted.error?.message??(converted.status?converted.stderr?.slice(-1000):null)};}
  const mode=production?'production':performanceOnly?'performance':'development',stem=production?'furniture-production':performanceOnly?'furniture-performance':'furniture-browser';
  const result={generatedAt:new Date().toISOString(),origin,mode,environment:'Installed Chrome headless, ANGLE SwiftShader, DPR1; 390px is touch emulation. Real GPU, physical mobile and Safari not tested.',measurementLimits:'Frame intervals include diagnostics and are not isolated CPU/GPU time. Per-family texture dimensions estimate memory, with no unproven cross-family sharing. Local warm-server timings are not internet cold starts.',summary:{passed:checks.filter(c=>c.passed).length,failed:checks.filter(c=>!c.passed).length},checks,observations,runtime,requests};
  await fs.writeFile(path.join(output,`${stem}.json`),JSON.stringify(result,null,2)+'\n');await fs.writeFile(path.join(output,`${stem.toUpperCase().replaceAll('-','_')}.md`),['# v0.6A Furniture Browser Evidence','',`Mode: ${mode}`,`Generated: ${result.generatedAt}`,`Result: ${result.summary.passed} passed; ${result.summary.failed} failed.`,'','All application state changes use native browser input or navigation. Diagnostics only observe. Fault fallbacks are never counted as successful formal asset installation.','',result.environment,result.measurementLimits,'','| Check | Result |','| --- | --- |',...checks.map(c=>`| ${c.name} | ${c.passed?'PASS':'FAIL'} |`),'',...checks.filter(c=>!c.passed).map(c=>`## ${c.name}\n\n\`\`\`\n${c.error}\n\`\`\``),''].join('\n'));console.log(`RESULT ${result.summary.passed} passed; ${result.summary.failed} failed`);
}
